data:
  # 选择默认的角色，可选的参考同目录的 角色列表.txt，也可以在对话中调整
  character: "派蒙_ZH"
  #这几个不懂不用调
  sdp_radio: 0.2
  ns: 0.5
  nsw: 0.9
  audio_speed: 1 # 语音播放速度
  sen_stop: 0.2
  para_stop: 1
  emotion: "Happy"
  weight: 0.7

# 是否默认开启语音功能，默认为False，即不开启，True为默认开启，看你喜好
voice_switch: True




# data:
#   # 选择默认的角色，可选的参考同目录的 角色列表.txt，也可以在对话中调整
#   character: "派蒙_ZH"
#   #这几个不懂不用调
#   sdp_radio: 0.2
#   ns: 0.5
#   nsw: 0.9
#   audio_speed: 1 # 语音播放速度
#   emotion: "Happy"
#   weight: 0.7

# # 是否默认开启语音功能，默认为False，即不开启，True为默认开启，看你喜好
# voice_switch: True
